# Generated by Django 6.1 on 2026-08-29 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_page", "0002_author_book_delete_geeks"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="id",
            field=models.BigIntegerField(
                primary_key=True, serialize=False, unique=True
            ),
        ),
    ]
