# Generated by Django 6.1 on 2026-08-29 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_page", "0003_alter_book_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="ValidatedURL",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name="author",
            name="b_day",
            field=models.DateTimeField(),
        ),
    ]
