# Generated by Django 6.1 on 2026-08-29 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_page", "0004_validatedurl_alter_author_b_day"),
    ]

    operations = [
        migrations.CreateModel(
            name="URLshort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("org", models.URLField()),
                ("slug", models.CharField(max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.DeleteModel(
            name="ValidatedURL",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="book",
        ),
    ]
