# Generated by Django 6.1 on 2026-08-29 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "profile_page",
            "0005_urlshort_remove_book_author_delete_validatedurl_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="urlshort",
            old_name="org",
            new_name="url",
        ),
    ]
