# Generated by Django 6.1 on 2026-08-30 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profile_page", "0006_rename_org_urlshort_url"),
    ]

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=20)),
                ("author", models.CharField(max_length=10)),
                ("desc", models.TextField(max_length=200)),
            ],
        ),
    ]
