import { useEffect, useMemo, useState } from 'react';
import { api } from './services/api';

const emptyTask = { title: '', description: '', status: 'Todo', priority: 'Medium', dueDate: '' };
const formatDate = (date) => new Intl.DateTimeFormat('en', { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(date));

function Auth({ onAuth }) {
  const [mode, setMode] = useState('login');
  const [form, setForm] = useState({ name: '', email: '', password: '', confirmPassword: '' });
  const [error, setError] = useState(''); 
  const [loading, setLoading] = useState(false);
  const submit = async (event) => { event.preventDefault(); setError(''); if (mode === 'register' && form.password !== form.confirmPassword) return setError('Passwords do not match'); setLoading(true); try { const result = await (mode === 'login' ? api.login(form) : api.register(form)); onAuth(result); } catch (err) { setError(err.message); } finally { setLoading(false); } };
  return <main className="auth-shell"><section className="auth-copy"><div className="brand"><span>✓</span> TaskFlow</div><h1>Focus on what<br />matters most.</h1><p>A calm, capable workspace for turning plans into progress.</p><div className="orbit orbit-one" /><div className="orbit orbit-two" /></section><section className="auth-panel"><form className="auth-form" onSubmit={submit}><p className="eyebrow">WELCOME TO TASKFLOW</p><h2>{mode === 'login' ? 'Welcome back' : 'Create your account'}</h2><p className="muted">{mode === 'login' ? 'Sign in to continue to your workspace.' : 'Start organising your best work today.'}</p>{error && <div className="error">{error}</div>}{mode === 'register' && <label>Name<input required value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} placeholder="Your name" /></label>}<label>Email address<input required type="email" value={form.email} onChange={(e) => setForm({ ...form, email: e.target.value })} placeholder="you@example.com" /></label><label>Password<input required type="password" minLength="6" value={form.password} onChange={(e) => setForm({ ...form, password: e.target.value })} placeholder="At least 6 characters" /></label>{mode === 'register' && <label>Confirm password<input required type="password" value={form.confirmPassword} onChange={(e) => setForm({ ...form, confirmPassword: e.target.value })} placeholder="Repeat your password" /></label>}<button className="primary full" disabled={loading}>{loading ? 'Please wait…' : mode === 'login' ? 'Sign in' : 'Create account'} <span>→</span></button><p className="switch">{mode === 'login' ? "Don't have an account?" : 'Already have an account?'} <button type="button" onClick={() => { setMode(mode === 'login' ? 'register' : 'login'); setError(''); }}>{mode === 'login' ? 'Create one' : 'Sign in'}</button></p></form></section></main>;
}

function TaskForm({ task, close, save }) {
  const [form, setForm] = useState(task || emptyTask); const [error, setError] = useState(''); const [busy, setBusy] = useState(false);
  const submit = async (e) => { e.preventDefault(); setBusy(true); setError(''); try { await save(form); close(); } catch (err) { setError(err.message); } finally { setBusy(false); } };
  return <div className="modal-wrap"><form className="modal" onSubmit={submit}><div className="modal-title"><div><p className="eyebrow">TASK DETAILS</p><h2>{task ? 'Edit task' : 'Create a task'}</h2></div><button type="button" className="icon-btn" onClick={close}>×</button></div>{error && <div className="error">{error}</div>}<label>Title<input required value={form.title} onChange={(e) => setForm({ ...form, title: e.target.value })} placeholder="What needs to be done?" /></label><label>Description<textarea value={form.description} onChange={(e) => setForm({ ...form, description: e.target.value })} placeholder="Add a little context…" /></label><div className="field-grid"><label>Status<select value={form.status} onChange={(e) => setForm({ ...form, status: e.target.value })}><option>Todo</option><option>In Progress</option><option>Done</option></select></label><label>Priority<select value={form.priority} onChange={(e) => setForm({ ...form, priority: e.target.value })}><option>Low</option><option>Medium</option><option>High</option></select></label></div><label>Due date<input required type="date" value={form.dueDate ? form.dueDate.slice(0, 10) : ''} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} /></label><div className="modal-actions"><button type="button" className="secondary" onClick={close}>Cancel</button><button className="primary" disabled={busy}>{busy ? 'Saving…' : 'Save task'}</button></div></form></div>;
}

function Dashboard({ data, tasks, openNew, setView }) { const by = data?.byStatus || {}; return <><div className="page-heading"><div><p className="eyebrow">OVERVIEW</p><h1>Good morning, {JSON.parse(localStorage.getItem('taskflow_user') || '{}').name?.split(' ')[0] || 'there'}.</h1><p className="muted">Here’s a clear view of your work.</p></div><button className="primary" onClick={openNew}>+ Create task</button></div><section className="stats">{[['All tasks', data?.totalTasks || 0, '◫'], ['Completed', data?.completedTasks || 0, '✓'], ['In progress', by['In Progress'] || 0, '↗'], ['To do', by.Todo || 0, '○']].map(([label, number, icon]) => <article className="stat" key={label}><span className="stat-icon">{icon}</span><p>{label}</p><strong>{number}</strong></article>)}</section><section className="dashboard-grid"><article className="panel progress-panel"><div className="panel-header"><div><h2>Your progress</h2><p className="muted">Tasks completed this cycle</p></div><strong className="percentage">{data?.completionPercentage || 0}%</strong></div><div className="progress"><i style={{ width: `${data?.completionPercentage || 0}%` }} /></div><div className="status-bars">{Object.entries({ Todo: by.Todo || 0, 'In progress': by['In Progress'] || 0, Completed: by.Done || 0 }).map(([label, count]) => <div key={label}><span>{label}</span><b><i style={{ width: `${data?.totalTasks ? (count / data.totalTasks) * 100 : 0}%` }} /></b><em>{count}</em></div>)}</div></article><article className="panel focus-panel"><div className="panel-header"><div><h2>Up next</h2><p className="muted">Your nearest deadlines</p></div><button className="text-btn" onClick={() => setView('tasks')}>View all</button></div>{tasks.slice(0, 4).map((task) => <div className="mini-task" key={task._id}><span className={`dot ${task.priority.toLowerCase()}`} /><div><strong>{task.title}</strong><small>Due {formatDate(task.dueDate)}</small></div><span className={`badge ${task.status.toLowerCase().replace(' ', '-')}`}>{task.status}</span></div>)}{!tasks.length && <p className="empty">Nothing is due yet. Enjoy the calm.</p>}</article></section></>;
}

function Tasks({ tasks, meta, filters, setFilters, refresh, edit, openNew }) { const [deleting, setDeleting] = useState(''); const remove = async (id) => { if (!confirm('Delete this task?')) return; setDeleting(id); try { await api.deleteTask(id); refresh(); } finally { setDeleting(''); } }; return <><div className="page-heading"><div><p className="eyebrow">TASKS</p><h1>Keep work moving.</h1><p className="muted">Plan, prioritise, and finish with confidence.</p></div><button className="primary" onClick={openNew}>+ Create task</button></div><section className="filters panel"><input className="search" value={filters.search} onChange={(e) => setFilters({ ...filters, search: e.target.value, page: 1 })} placeholder="⌕  Search tasks" /><select value={filters.status} onChange={(e) => setFilters({ ...filters, status: e.target.value, page: 1 })}><option value="">All statuses</option><option>Todo</option><option>In Progress</option><option>Done</option></select><select value={filters.priority} onChange={(e) => setFilters({ ...filters, priority: e.target.value, page: 1 })}><option value="">All priorities</option><option>High</option><option>Medium</option><option>Low</option></select><select value={`${filters.sort}-${filters.order}`} onChange={(e) => { const [sort, order] = e.target.value.split('-'); setFilters({ ...filters, sort, order, page: 1 }); }}><option value="dueDate-asc">Due date ↑</option><option value="dueDate-desc">Due date ↓</option><option value="priority-desc">Priority ↓</option><option value="priority-asc">Priority ↑</option></select></section><section className="task-list panel">{tasks.map((task) => <article className="task-row" key={task._id}><button className={`check ${task.status === 'Done' ? 'checked' : ''}`} onClick={async () => { if (task.status !== 'Done') { await api.completeTask(task._id); refresh(); } }}>{task.status === 'Done' ? '✓' : ''}</button><div className="task-main"><strong>{task.title}</strong>{task.description && <p>{task.description}</p>}<small>Due {formatDate(task.dueDate)}</small></div><span className={`priority ${task.priority.toLowerCase()}`}>{task.priority}</span><span className={`badge ${task.status.toLowerCase().replace(' ', '-')}`}>{task.status}</span><div className="row-actions"><button onClick={() => edit(task)}>Edit</button><button className="danger" disabled={deleting === task._id} onClick={() => remove(task._id)}>{deleting === task._id ? '…' : 'Delete'}</button></div></article>)}{!tasks.length && <div className="empty large"><strong>No tasks found</strong><p>Try adjusting your filters or create a new task.</p></div>}</section>{meta.totalPages > 1 && <div className="pagination"><button disabled={filters.page === 1} onClick={() => setFilters({ ...filters, page: filters.page - 1 })}>← Previous</button><span>Page {meta.page} of {meta.totalPages}</span><button disabled={filters.page === meta.totalPages} onClick={() => setFilters({ ...filters, page: filters.page + 1 })}>Next →</button></div>}</>;
}

function App() {
  const [session, setSession] = useState(() => { try { return JSON.parse(localStorage.getItem('taskflow_user')); } catch { return null; } }); const [view, setView] = useState('dashboard'); const [dark, setDark] = useState(() => localStorage.getItem('taskflow_theme') === 'dark'); const [tasks, setTasks] = useState([]); const [meta, setMeta] = useState({}); const [data, setData] = useState(null); const [error, setError] = useState(''); const [loading, setLoading] = useState(false); const [modal, setModal] = useState(null); const [filters, setFilters] = useState({ search: '', status: '', priority: '', sort: 'dueDate', order: 'asc', page: 1, limit: 10 });
  useEffect(() => { document.documentElement.dataset.theme = dark ? 'dark' : 'light'; localStorage.setItem('taskflow_theme', dark ? 'dark' : 'light'); }, [dark]);
  const load = async () => { if (!session) return; setLoading(true); setError(''); try { const [taskResult, analytics] = await Promise.all([api.tasks(filters), api.analytics()]); setTasks(taskResult.tasks); setMeta(taskResult); setData(analytics); } catch (err) { setError(err.message); if (/session|Authentication/.test(err.message)) logout(); } finally { setLoading(false); } };
  useEffect(() => { load(); }, [session, filters]);
  const login = (result) => { localStorage.setItem('taskflow_token', result.token); localStorage.setItem('taskflow_user', JSON.stringify(result.user)); setSession(result.user); };
  const logout = () => { localStorage.removeItem('taskflow_token'); localStorage.removeItem('taskflow_user'); setSession(null); };
  const save = async (form) => { if (modal?._id) await api.updateTask(modal._id, form); else await api.createTask(form); setFilters({ ...filters, page: 1 }); await load(); };
  if (!session) return <Auth onAuth={login} />;
  return <div className="app-shell"><aside><div className="brand"><span>✓</span> TaskFlow</div><nav><button className={view === 'dashboard' ? 'active' : ''} onClick={() => setView('dashboard')}><span>▦</span> Dashboard</button><button className={view === 'tasks' ? 'active' : ''} onClick={() => setView('tasks')}><span>☷</span> My tasks</button></nav><div className="side-bottom"><button onClick={() => setDark(!dark)}><span>{dark ? '☀' : '◐'}</span>{dark ? 'Light mode' : 'Dark mode'}</button><div className="profile"><span>{session.name[0]}</span><div><strong>{session.name}</strong><small>{session.email}</small></div><button onClick={logout} title="Sign out">↪</button></div></div></aside><main className="content"><header className="mobile-head"><div className="brand"><span>✓</span> TaskFlow</div><button className="icon-btn" onClick={logout}>↪</button></header>{error && <div className="error global">{error}</div>}{loading ? <div className="loader"><i /> Loading your workspace…</div> : view === 'dashboard' ? <Dashboard data={data} tasks={tasks} openNew={() => setModal(emptyTask)} setView={setView} /> : <Tasks tasks={tasks} meta={meta} filters={filters} setFilters={setFilters} refresh={load} edit={setModal} openNew={() => setModal(emptyTask)} />}</main>{modal && <TaskForm task={modal._id ? modal : null} close={() => setModal(null)} save={save} />}</div>;
}
export default App;
